language: java

jdk:
- oraclejdk7

cache:
  directories:
  - "$HOME/.m2/repository"

script:
  - mvn cobertura:cobertura
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -t "ea6ef0e7-e974-45c4-b381-335cdbf14ce0"
